name: Build and push docker image

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name for push
        run: echo "normalized_branch_name=$(stripped=${GITHUB_REF##*/} && echo ${stripped/\//-})" >> $GITHUB_ENV
        if: github.event_name == 'push'

      - name: Extract branch name for pull request
        run: echo "normalized_branch_name=$(stripped=${PR_REF#refs/heads/} && echo ${stripped/\//-})" >> $GITHUB_ENV
        if: github.event_name == 'pull_request'
        env:
          PR_REF: ${{ github.event.pull_request.head.ref }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Check out
        id: checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            ghcr.io/dlcs/lustre-watcher:${{ github.sha }}
            ghcr.io/dlcs/lustre-watcher:${{ env.normalized_branch_name }}